### ISSUE TITLE
the app just crashes on startup

### ISSUE THREAD

**Issue by real-hazem** [FossifyOrg/Phone#242]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.2.0

### Affected Android/Custom ROM version

GrapheneOS build 2024091900

### Affected device model

Google Pixel 7 Pro

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Open the app.
2. App crashes.
3. Cry.

### Expected behavior

The app should open without crashing.

### Actual behavior

The app just crashes.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/8f4c8172-1272-4df2-b683-4af72b14bc36

### Additional information

crash logs that i dont understand:
```
type: crash
osVersion: google/cheetah/cheetah:14/AP2A.240905.003/2024091900:user/release-keys
package: org.fossify.phone:4
process: org.fossify.phone
processUptime: 453 + 246 ms
installer: com.looker.droidify

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toString()' on a null object reference
	at S3.y.H(SourceFile:25)
	at K.c.m(SourceFile:113)
	at H4.y.e(SourceFile:169)
	at j4.j.f(SourceFile:26)
	at K1.r0.i(SourceFile:1115)
	at K1.M.b(SourceFile:63)
	at androidx.recyclerview.widget.LinearLayoutManager.X0(SourceFile:1)
	at androidx.recyclerview.widget.LinearLayoutManager.K0(SourceFile:49)
	at androidx.recyclerview.widget.LinearLayoutManager.e0(SourceFile:821)
	at androidx.recyclerview.widget.RecyclerView.r(SourceFile:74)
	at androidx.recyclerview.widget.RecyclerView.p(SourceFile:72)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:8)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at Y1.i.onLayout(SourceFile:259)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(SourceFile:62)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.r(SourceFile:392)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:47)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:807)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4562)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3830)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2718)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9937)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:945)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by real-hazem** [comment]
Didn't check for closed issues, oops.
