### ISSUE TITLE
App crashes and refuses to open after receiving call from a particular spam number

### ISSUE THREAD

**Issue by adarsh1001** [FossifyOrg/Phone#260]
### Checklist

- [X] I can reproduce the bug with the latest version given [here](https://github.com/FossifyOrg/Phone/releases/latest).
- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Phone/issues) or [closed](https://github.com/FossifyOrg/Phone/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Phone/discussions) or [closed](https://github.com/FossifyOrg/Phone/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

### Affected app version

1.2.0

### Affected Android/Custom ROM version

Android 14

### Affected device model

Nothing Phone (2)

### How did you install the app?

F-Droid / IzzyOnDroid

### Steps to reproduce the bug

1. Open the app
2. Dial a number starting with +697xxxxxxxx. Put anything in the 8x's. I actually got an incoming call from such a number.
3. App will crash and refuse to open.
4. To fix, install another Phone app like Koler and delete the number from recents.

### Expected behavior

For app to not crash.

### Actual behavior

App crashes and refuses to open.

### Screenshots/Screen recordings

Provided logs instead, video will just show app crashing.

### Additional information

Logs:

```
FATAL EXCEPTION: main
Process: org.fossify.phone, PID: 20061
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toString()' on a null object reference
	at S3.y.H(SourceFile:25)
	at K.c.m(SourceFile:113)
	at H4.y.e(SourceFile:169)
	at j4.j.f(SourceFile:26)
	at K1.r0.i(SourceFile:1115)
	at K1.M.b(SourceFile:63)
	at androidx.recyclerview.widget.LinearLayoutManager.X0(SourceFile:1)
	at androidx.recyclerview.widget.LinearLayoutManager.K0(SourceFile:49)
	at androidx.recyclerview.widget.LinearLayoutManager.e0(SourceFile:821)
	at androidx.recyclerview.widget.RecyclerView.r(SourceFile:74)
	at androidx.recyclerview.widget.RecyclerView.p(SourceFile:72)
	at androidx.recyclerview.widget.RecyclerView.onLayout(SourceFile:8)
	at android.view.View.layout(View.java:24430)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:24430)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at Y1.i.onLayout(SourceFile:259)
	at android.view.View.layout(View.java:24430)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(SourceFile:62)
	at android.view.View.layout(View.java:24430)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.r(SourceFile:392)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(SourceFile:47)
	at android.view.View.layout(View.java:24430)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24430)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24430)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24430)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:24430)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:789)
	at android.view.View.layout(View.java:24430)
	at android.view.ViewGroup.layout(ViewGroup.java:6440)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4317)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3642)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2514)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9398)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1475)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1484)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1076)
	at android.view.Choreographer.doFrame(Choreographer.java:1004)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1451)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8291)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:557)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
```

**Comment by adarsh1001** [comment]
More info on +697 numbers, it apparently indicates voice call over IP and there's an advisory on it:
https://thethaiger.com/hot-news/crime/thailand-dont-answer-calls-starting-with-697-its-a-scam

Anyway, app shouldn't crash.

**Comment by Aga-C** [comment]
@SolsticeSpectrum No need for logs, we are aware of this issue, and we're able to reproduce it. For now, to avoid crashing, please use any other app to clear the entry from history.

**Comment by naveensingh** [comment]
@adarsh1001 can you please check if this is fixed now in version 1.3.0?

**Comment by adarsh1001** [comment]
Yes fixed now @naveensingh. Thanks! Can close the issue.

**Comment by SolsticeSpectrum** [comment]
Can confirm, it works now. It also doesn't save invalid numbers in call history

**Comment by naveensingh** [comment]
Ok, thanks for the confirmation!
